export default {
  background: require('../assets/background.jpg'),
  uitLogo: require('../assets/Logo_UIT_Web_Transparent.png'),
  
  personIcon: require('../assets/icon/Person.png'),
  keyIcon: require('../assets/icon/Key.png'),
  atSignIcon: require('../assets/icon/At_sign.png'),
  cloudIcon: require('../assets/icon/Cloud.png'),
  chevronRightIcon: require('../assets/icon/Chevron_Right.png'),
  documentIcon: require('../assets/icon/Document.png'),
  doorIcon: require('../assets/icon/Door.png'),
  emailIcon: require('../assets/icon/Email.png'),
  exportIcon: require('../assets/icon/Export.png'),
  fingerprintIcon: require('../assets/icon/Fingerprint.png'),
  globeIcon: require('../assets/icon/Globe.png'),
  lockIcon: require('../assets/icon/Lock.png'),
  passportIcon: require('../assets/icon/Passport.png'),
  phoneIcon: require('../assets/icon/Phone.png'),
  menuIcon: require('../assets/icon/Menu.png'),
  searchIcon: require('../assets/icon/Search.png'),
  groupIcon: require('../assets/icon/People.png'),
  chatIcon: require('../assets/icon/Chat.png'),
  bellIcon: require('../assets/icon/Notification.png'),
};
